version: '3.8'

networks:
  restaurant-net:

services:
  restaurant-db:
    image: 'bitnami/mariadb:latest'
    container_name: restaurant-db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=restaurant
      - MARIADB_PASSWORD=secret
      - MARIADB_DATABASE=restaurant
    volumes:
        - './mariadb:/bitnami/mariadb'
    networks:
      - restaurant-net
    ports:
      - 3306:3306
      
  restaurant-api:
    image: docker.io/bitnami/laravel:8
    container_name: restaurant-api
    user: bitnami
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=restaurant-db
      - DB_PORT=3306
      - DB_USERNAME=restaurant
      - DB_PASSWORD=secret
      - DB_DATABASE=restaurant
    volumes:
      - './src:/app'
    depends_on:
      - restaurant-db
    networks:
      - restaurant-net

  # restaurant-frontend:
  #   build:
  #     context: ./node
  #     dockerfile: node.Dockerfile
  #   container_name: restaurant-frontend
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - './src:/app'
  #   depends_on:
  #     - restaurant-db
  #     - restaurant-api
  #   networks:
  #     - restaurant-net
    
  # npm:
  #   build:
  #     context: ./node
  #     dockerfile: npm.Dockerfile
  #   container_name: npm
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - './node/src:/app'
  #   depends_on:
  #     - restaurant-db
  #     - restaurant-api
  #   networks:
  #     - restaurant-net